'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'ar' | 'en'

interface LanguageContextType {
  lang: Language
  setLang: (lang: Language) => void
  t: (key: string) => string
  isRtl: boolean
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  ar: {
    // Navigation
    nav_home: 'الرئيسية',
    nav_about: 'عن الدكتور',
    nav_steps: 'خطوات الحجز',
    nav_packages: 'الباقات',
    nav_testimonials: 'آراء المرضى',
    nav_faq: 'الأسئلة الشائعة',
    nav_start: 'ابدأ الاستشارة',
    logo_sub: 'استشاري جراحة العظام والعمود الفقري أونلاين',
    footer_desc: 'منصة استشارات طبية متكاملة مع د. خالد بترجي، لتقديم رعاية صحية ممتازة وتجربة استشارية آمنة وموثوقة من منزلك.',
    footer_links: 'روابط سريعة',
    footer_rights: 'جميع الحقوق محفوظة',

    // Hero Section
    hero_badge: 'مركز بترجي للاستشارات الطبية التخصصية',
    hero_title_dr: 'د. خالد بترجي',
    hero_title_title: 'استشاري جراحة العظام والعمود الفقري',
    hero_title_sub: 'رعاية طبية فائقة لجراحات الركبة والمفاصل الصناعية والمناظير أونلاين من منزلك',
    hero_para: 'أول منصة استشارات طبية متكاملة تجمع بين خبرة الاستشاريين وسهولة التقنية. احجز استشارتك المرئية في دقائق، وارفع فحوصاتك وتقاريرك بخصوصية تامة وتلقى التشخيص والخطة العلاجية من منزلك.',
    hero_btn_start: 'ابدأ الاستشارة الآن',
    hero_btn_about: 'تعرّف على الدكتور',
    hero_status_online: 'رئيس مجلس إدارة المركز (متاح للحجز)',

    // Hero Stats
    stat_experience_num: '35+',
    stat_experience_label: 'سنة من الخبرة',
    stat_experience_desc: 'في جراحة العظام والعمود الفقري',
    stat_online_num: '100%',
    stat_online_label: 'استشارة أون لاين',
    stat_online_desc: 'مرئية، آمنة ومريحة',
    stat_satisfaction_num: '1,500+',
    stat_satisfaction_label: 'مريض تم علاجهم',
    stat_satisfaction_desc: 'بنسبة رضا تفوق 98%',

    // Expertise Bar
    exp_joints: 'جراحة العظام والعمود الفقري',
    exp_scopes: 'المناظير الجراحية',
    exp_pain: 'علاج الآلام المزمنة',
    exp_rehab: 'تأهيل ما بعد العمليات',
    exp_online: 'استشارات أون لاين',

    // Achievement Counters
    counter_patients_label: 'مريض',
    counter_patients_sub: 'تمت استشارتهم',
    counter_experience_label: 'عاماً',
    counter_experience_sub: 'خبرة في المجال الطبي',
    counter_satisfaction_label: 'رضا المرضى',
    counter_satisfaction_sub: 'نسبة تقييمات إيجابية',
    counter_response_label: 'ساعة',
    counter_response_sub: 'الرد على الاستفسارات',

    // Doctor Qualifications
    qual_label: 'المؤهلات العلمية',
    qual_title: 'خبرة تمتد لأكثر من ثلاثة عقود',
    qual_desc: 'يتمتع الدكتور خالد بترجي بسيرة ذاتية حافلة بالإنجازات الأكاديمية والعملية في مجال جراحة العظام والعمود الفقري، مع أكثر من 35 عاماً من الخبرة المتراكمة.',
    qual_btn: 'احجز استشارتك',
    qual_1991_title: 'تأسيس مركز بترجي الطبي',
    qual_1991_inst: 'رؤية لتقديم أفضل الخدمات الطبية التخصصية',
    qual_2012_title: 'إطلاق العيادات المتكاملة',
    qual_2012_inst: 'توسعة الأقسام لتشمل العمود الفقري والروماتيزم والتأهيل',
    qual_2020_title: 'التكامل الرقمي الكامل',
    qual_2020_inst: 'تحويل جميع الاستشارات إلى استشارات مرئية تفاعلية عن بعد',
    qual_2026_title: 'نظام الاستشارات المطور',
    qual_2026_inst: 'إطلاق المنصة الجديدة وتفعيل ميزات التخزين الطبي الآمن وتوصيل الأدوية',

    // How it Works
    steps_label: 'خطوات الحجز',
    steps_title: 'كيف تعمل الخدمة؟',
    steps_subtitle: 'من التسجيل إلى الجلسة مع الدكتور في 4 خطوات بسيطة',
    step1_title: 'احجز الاستشارة',
    step1_desc: 'اختر الباقة الطبية المناسبة لحالتك لبدء حجز موعدك',
    step2_title: 'سجّل بياناتك الطبية',
    step2_desc: 'املأ معلوماتك الشخصية وارفع الأشعة والتحاليل في دقائق',
    step3_title: 'سدد الرسوم بأمان',
    step3_desc: 'ادفع عبر بوابات الدفع الإلكتروني المعتمدة والسريعة',
    step4_title: 'احجز موعدك وتواصل',
    step4_desc: 'اختر الموعد المناسب لجلستك المرئية المباشرة مع الطبيب',

    // Packages & Pricing
    pricing_label: 'الباقات والأسعار',
    pricing_title: 'اختر الباقة المناسبة لك',
    pricing_subtitle: 'استشارات مرنة بأسعار تنافسية تناسب جميع الحالات',
    pkg_popular: 'الأكثر طلباً',
    pkg_basic_label: 'باقة أساسية',
    pkg_advanced_label: 'باقة مطورة',
    pkg_btn_choose: 'اختر الباقة',
    pkg_btn_book: 'احجز الآن',
    currency_sar: 'ريال',
    
    pkg_basic_title: 'الكشف الأساسي',
    pkg_basic_desc: 'جلسة استشارية شاملة لمدة 30 دقيقة مع الطبيب لتقييم حالتك وتشخيصها بدقة.',
    pkg_basic_f1: 'كشفية أساسية مع الاستشاري',
    pkg_basic_f2: 'عرض وتحليل الأشعة والتحاليل',
    pkg_basic_f3: 'تشخيص طبي دقيق للحالة',
    pkg_basic_f4: 'مدة الجلسة: 30 دقيقة',
    pkg_basic_f5: 'متابعة مجانية لمدة 10 أيام',

    pkg_comprehensive_title: 'الكشف الشامل والخطة العلاجية',
    pkg_comprehensive_desc: 'استشارة موسعة مع إعداد برنامج علاجي متكامل وتقييم الحاجة للجراحة.',
    pkg_comprehensive_f1: 'كل ما في الباقة الأساسية',
    pkg_comprehensive_f2: 'إعداد برنامج علاجي متكامل',
    pkg_comprehensive_f3: 'تقييم الحاجة للجراحة',
    pkg_comprehensive_f4: 'مناقشة الخيارات البديلة والجراحية',
    pkg_comprehensive_f5: 'متابعة أولى مجانية بعد العملية',

    pkg_followup_title: 'باقات المتابعة المتعددة',
    pkg_followup_desc: 'جلسات متعددة بسعر مخفّض للمرضى المحتاجين لمتابعة مستمرة بعد العمليات.',
    pkg_followup_f1_template: 'باقة 3 جلسات بقيمة {p3} ريال',
    pkg_followup_f2_template: 'باقة 4 جلسات بقيمة {p4} ريال',
    pkg_followup_f3: 'توفير يصل إلى 200 ريال',
    pkg_followup_f4: 'متابعة ما بعد الجراحة وإصابات الملاعب',
    pkg_followup_f5: 'مرونة عالية في حجز المواعيد',

    // Why Choose Us
    why_label: 'لماذا د. خالد بترجي؟',
    why_title: 'رعاية طبية بمعايير عالمية من منزلك',
    why_desc: 'نضعك في قلب الرعاية الصحية. منصة متكاملة تجمع بين الخبرة الطبية والتقنية الحديثة لتوفير تجربة استشارية سلسة وآمنة.',
    why_btn: 'ابدأ الآن',
    why_stat_patients: 'مريض',
    why_stat_satisfaction: 'رضا المرضى',
    why_stat_response: 'ساعة للرد',
    why_trust_p1_num: 'بورد معتمد',
    why_trust_p1_label: 'بورد كندي وزمالة بريطانية',
    why_trust_p2_num: 'أمان تام',
    why_trust_p2_label: 'تشفير وحماية سرية الملفات',
    why_trust_p3_num: 'وصفة ذكية',
    why_trust_p3_label: 'وصفتك الطبية معتمدة رقمياً',
    
    why_f1_title: 'خبرة طبية عريقة',
    why_f1_desc: 'يحمل د. خالد بترجي درجات البورد والزمالات الكندية والبريطانية مع خبرة طبية تفوق 35 عاماً.',
    why_f2_title: 'خصوصية تامة للملفات',
    why_f2_desc: 'تشفير كامل لملفاتك وأشعاتك الطبية وفقاً لأعلى معايير الأمن السيبراني الطبية.',
    why_f3_title: 'جدولة مواعيد فورية',
    why_f3_desc: 'اختر وقتك المناسب مباشرة من جدول الطبيب المتاح دون فترات انتظار.',
    why_f4_title: 'دعم جميع الصيغ الطبية',
    why_f4_desc: 'ارفع تقاريرك وأشعاتك بسهولة فائقة بمختلف الصيغ الطبية بما فيها ملفات DICOM.',
    why_f5_title: 'توصيل الوصفة للمنزل',
    why_f5_desc: 'نوفر خدمة إرسال وصفتك الطبية المعتمدة رقمياً وتوصيل الأدوية مباشرة لباب بيتك.',
    why_f6_title: 'بوابة دفع آمنة ومعتمدة',
    why_f6_desc: 'خيارات دفع سعودية موثوقة تدعم بطاقات مدى، فيزا، ماستركارد، وأبل باي.',

    // Testimonials
    test_label: 'آراء المرضى',
    test_title: 'ماذا يقول مرضانا؟',
    test_1_text: 'المركز يقدم رعاية ممتازة جداً وخبرة طبية متميزة. استشرت د. خالد بترجي بخصوص عملية الركبة وكان تشخيصه دقيقاً جداً وأراحني كثيراً. وفر علي عناء السفر.',
    test_1_name: 'عبدالرحمن العتيبي',
    test_1_title: 'مريض (عيادة جراحة المفاصل)',
    test_2_text: 'تجربة حجز سهلة وسريعة للغاية، والأروع هو إمكانية رفع الأشعة وملفات الرنين المغناطيسي ليقوم د. خالد بترجي بتحليلها ووصف العلاج المناسب لي دون الحاجة لمغادرة المنزل.',
    test_2_name: 'نورة الدوسري',
    test_2_title: 'مريضة (جراحة العظام)',
    test_3_text: 'بعد إصابتي في الركبة، تواصلت مع د. خالد بترجي وأعدّ لي برنامج تأهيل حركي منزلي رائع وتابع معي خطوة بخطوة حتى عدت لممارسة الرياضة بشكل طبيعي.',
    test_3_name: 'فهد السبيعي',
    test_3_title: 'مريض (جراحة العظام والعمود الفقري)',

    // Medical Library
    lib_label: 'المكتبة الطبية',
    lib_title: 'موارد صحية لك',
    lib_desc: 'مقالات وإرشادات طبية من إعداد د. خالد بترجي لمساعدتك في رحلة علاجك',
    read_time_suffix: 'دقائق قراءة',

    // FAQ
    faq_label: 'الأسئلة الشائعة',
    faq_title: 'كل ما تريد معرفته عن الاستشارة',
    faq_desc: 'إجابات سريعة عن أكثر الأسئلة شيوعاً. إن كان لديك سؤال آخر، لا تتردد في التواصل معنا.',
    faq_1_q: 'كيف يمكنني حجز استشارة في مركز بترجي؟',
    faq_1_a: 'العملية بسيطة للغاية وتستغرق أقل من 5 دقائق: املأ بياناتك الطبية وأرفق الأشعة إن وجدت، قم بسداد رسوم الاستشارة بأمان، ثم اختر الموعد المناسب لك من جدول الطبيب المباشر لتلقي رابط الجلسة المرئية.',
    faq_2_q: 'ما هي تكلفة الاستشارة الطبية؟',
    faq_2_a_template: 'تختلف التكلفة حسب مستوى الكشف المختار: الكشف الأساسي بقيمة {p1} ريال، الكشف الشامل وإعداد الخطة العلاجية بقيمة {p2} ريال، كما تتوفر باقات للمتابعات المتعددة تبدأ من {p3} ريال لـ 3 جلسات.',
    faq_3_q: 'هل يمكنني مراجعة الطبيب مجاناً بعد الجلسة؟',
    faq_3_a: 'نعم، تشمل جميع الاستشارات الطبية كفترة مراجعة (متابعة مجانية) صالحة لمدة 10 أيام من تاريخ الجلسة الأساسية لمناقشة نتائج التحاليل أو تحديث خطة العلاج.',
    faq_4_q: 'هل خدمة توصيل الأدوية متاحة لجميع المرضى؟',
    faq_4_a: 'نعم، بعد استشارتك مع الطبيب، إذا قرر لك وصفة علاجية، يتم إرسالها لك إلكترونياً، ونوفر خيار توصيل الأدوية لباب منزلك بالتعاون مع كبرى الصيدليات المعتمدة.',
    faq_5_q: 'كيف أرفع الفحوصات وصور الأشعة الخاصة بي؟',
    faq_5_a: 'أثناء تعبئة نموذج الاستشارة، ستجد منطقة مخصصة لرفع الملفات، حيث يمكنك سحب وإفلات التقارير الطبية وصور الأشعة. يدعم نظامنا جميع الصيغ المعتمدة مثل PDF وJPG وPNG بالإضافة لصيغة DICOM للأشعات المتخصصة.',

    // Final CTA
    cta_badge: 'ابدأ رحلة علاجك اليوم',
    cta_title: 'استشر طبيبك الاستشاري من منزلك اليوم',
    cta_desc: 'احجز استشارتك الآن خلال دقائق وابدأ رحلة علاجك مع طبيبك الاستشاري. رعاية طبية تخصصية بمعايير عالمية في متناول يدك.',
    cta_btn: 'ابدأ الاستشارة',
    art_not_found: 'المقال غير موجود',
    art_not_found_desc: 'عذراً، المقال الذي تبحث عنه غير متوفر حالياً أو قد تم نقله.',
    art_back: 'العودة للرئيسية',
    art_written_by: 'كتب بواسطة:',
    art_published_in: 'نُشر في:',
    art_sidebar_q: 'هل تعاني من آلام المفاصل؟',
    art_sidebar_desc: 'احجز استشارتك الآن مع الدكتور خالد بترجي من منزلك لتلقي التشخيص الدقيق والخطة العلاجية المناسبة عبر محادثة آمنة.',
    art_sidebar_btn: 'ابدأ الاستشارة الآن',
    art_related: 'مقالات ذات صلة',

    // Doctor Dashboard Common
    dash_brand_name: 'مركز بترجي',
    dash_brand_sub: 'لوحة التحكم',
    dash_brand_mark: 'ب',
    dash_nav_title: 'التنقّل',
    dash_nav_requests: 'طلبات الاستشارات',
    dash_nav_settings: 'إعدادات العيادة',
    dash_doctor_section: 'الطبيب المعالج',
    dash_doctor_role: 'طبيب',
    dash_signout: 'تسجيل الخروج',
    dash_error_back: 'العودة للوحة التحكم',
    dash_error_title: 'حدث خطأ غير متوقع. يرجى تحديث الصفحة.',
    dash_gate_checking_login: 'جاري التحقق من تسجيل الدخول...',
    dash_gate_loading_consults: 'جاري تحميل الاستشارات...',
    dash_gate_loading_detail: 'جاري تحميل تفاصيل الاستشارة...',
    dash_gate_loading_dash: 'جاري تحميل لوحة التحكم...',

    // Dashboard Main Page
    dash_eyebrow: 'لوحة التحكم المشتركة',
    dash_title_requests: 'مركز بترجي للاستشارات الطبية',
    dash_title_settings: 'ضبط جدول العمل والعيادة',
    dash_subtitle_requests: 'متابعة طلبات وحجوزات الاستشارات بكفاءة ورؤية واضحة لكل حالة.',
    dash_subtitle_settings: 'تحديد أيام وساعات العمل ومدة الاستشارة لكل طبيب.',
    dash_total: 'إجمالي',
    dash_consultations: 'استشارة',
    dash_filter_status_label: 'الحالة:',
    dash_filter_status_all: 'الكل',
    dash_reset_filters: 'إعادة ضبط',
    dash_search_placeholder: 'ابحث باسم المريض، الجوال، أو سبب الشكوى...',
    dash_showing: 'عرض',
    dash_of: 'من',
    dash_table_patient: 'المريض',
    dash_table_complaint: 'سبب الاستشارة',
    dash_table_status: 'الحالة',
    dash_table_date: 'التاريخ',
    dash_empty_title: 'لا توجد استشارات مطابقة',
    dash_empty_desc: 'جرب تعديل خيارات التصفية أو البحث في الأعلى.',
    dash_patient_years: 'سنة',
    dash_save_success: 'تم حفظ إعدادات المواعيد وجدول العمل بنجاح!',
    dash_working_days: 'أيام العمل الأسبوعية',
    dash_daily_hours: 'ساعات الدوام اليومي',
    dash_start_time: 'بداية الدوام',
    dash_end_time: 'نهاية الدوام',
    dash_break_hours: 'فترة الاستراحة / الغداء',
    dash_break_start: 'بداية الاستراحة',
    dash_break_end: 'نهاية الاستراحة',
    dash_slot_duration: 'مدة الاستشارة (دقيقة)',
    dash_prices_title: 'أسعار الجلسات والاستشارات',
    dash_price_basic: 'سعر الكشف الأساسي (ريال)',
    dash_price_comprehensive: 'سعر الكشف الشامل والخطة العلاجية (ريال)',
    dash_price_pkg3: 'سعر باقة 3 جلسات متابعة (ريال)',
    dash_price_pkg4: 'سعر باقة 4 جلسات متابعة (ريال)',
    dash_price_promo: 'سعر باقة المتابعة المتعددة والعرض الترويجي (ريال)',
    dash_gcal_title: 'تكامل Google Calendar',
    dash_gcal_desc: 'عند ربط حساب Google Calendar، يتم إخفاء المواعيد المشغولة تلقائياً من المرضى، وإنشاء حدث في تقويمك عند حجز مريض لموعد جديد.',
    dash_gcal_connected: 'متصل',
    dash_gcal_disconnect: 'قطع الاتصال',
    dash_gcal_connect: 'ربط Google Calendar',
    dash_gcal_warning: 'لتفعيل التكامل، أضف بيانات اعتماد Google OAuth في متغيرات البيئة:',
    dash_save_changes: 'حفظ التعديلات وإعدادات الدوام',
    dash_saving: 'جاري الحفظ...',
    dash_slot_15: '15 دقيقة',
    dash_slot_30: '30 دقيقة',
    dash_slot_45: '45 دقيقة',
    dash_slot_60: '60 دقيقة (ساعة كاملة)',

    // Dashboard Detail Page
    dash_detail_back: 'العودة للوحة التحكم',
    dash_detail_title: 'تفاصيل استشارة:',
    dash_detail_doctor_kicker: 'الطبيب المعالج',
    dash_detail_appt_label: 'الموعد',
    dash_btn_start_review: 'بدء المراجعة',
    dash_btn_approve: 'قبول وتأكيد',
    dash_btn_ask_info: 'طلب معلومات',
    dash_btn_reject: 'رفض',
    dash_btn_start_close: 'بدء الاستشارة وإغلاقها',
    dash_btn_reschedule: 'إعادة جدولة',
    dash_btn_cancel: 'إلغاء',
    dash_btn_view_as_patient: 'عرض كالمريض',
    dash_panel_patient_info: 'بيانات المريض والشكوى',
    dash_info_name: 'الاسم',
    dash_info_phone: 'الجوال',
    dash_info_age: 'العمر',
    dash_chief_complaint_label: 'الشكوى الرئيسية',
    dash_panel_pain_eval: 'تقييم الألم',
    dash_pain_nature: 'طبيعة الألم',
    dash_pain_locations: 'أماكن الألم',
    dash_panel_files: 'الملفات المرفقة',
    dash_files_empty: 'لا توجد ملفات مرفقة',
    dash_id_card_label: 'بطاقة الهوية',
    dash_file_open: 'فتح',
    dash_panel_chat: 'المحادثة مع المريض',
    dash_chat_empty: 'لا توجد رسائل بعد. ابدأ المحادثة بإرسال رسالة أو اطلب معلومات.',
    dash_chat_me: 'أنا (الطبيب)',
    dash_chat_placeholder: 'اكتب رسالة للمريض...',
    dash_chat_send: 'إرسال',
    dash_chat_templates: 'قوالب جاهزة',
    dash_panel_notes: 'ملاحظات الطبيب (خاصة)',
    dash_notes_placeholder: 'ملاحظاتك الخاصة حول هذه الحالة...',
    dash_notes_save: 'حفظ الملاحظات',
    dash_notes_saved_at: 'تم الحفظ',
    dash_cancellation_reason_title: 'سبب الإلغاء/الرفض',
    dash_confirm_reschedule: 'إعادة جدولة الموعد',
    dash_confirm_new_date: 'التاريخ الجديد',
    dash_confirm_new_time: 'الوقت الجديد',
    dash_confirm_btn_confirm: 'تأكيد',
    dash_confirm_btn_cancel: 'إلغاء',
    dash_confirm_approve_title: 'تأكيد قبول الاستشارة',
    dash_confirm_approve_desc: 'سيتم قبول الاستشارة وتأكيد الموعد للمريض.',
    dash_confirm_approve_btn: 'تأكيد القبول',
    dash_confirm_approve_back: 'تراجع',
    dash_confirm_cancel_title: 'إلغاء الاستشارة',
    dash_confirm_cancel_placeholder: 'سبب الإلغاء (سيظهر للمريض)...',
    dash_confirm_cancel_btn: 'تأكيد الإلغاء',
    dash_confirm_reject_title: 'رفض طلب الاستشارة',
    dash_confirm_reject_placeholder: 'سبب الرفض (اختياري، سيظهر للمريض)...',
    dash_confirm_reject_btn: 'تأكيد الرفض',

    // Login Page
    dash_login_title: 'لوحة تحكم الطبيب',
    dash_login_sub: 'سجّل دخولك للوصول إلى الاستشارات وإدارة المواعيد',
    dash_login_email: 'البريد الإلكتروني',
    dash_login_password: 'كلمة المرور',
    dash_login_btn: 'تسجيل الدخول',
    dash_login_loading: 'جاري الدخول...',
    dash_login_error_missing: 'الرجاء إدخال البريد الإلكتروني وكلمة المرور.',
    dash_login_test_hint: 'للتجربة استخدم حساب الاختبار:',
    dash_login_fill_btn: 'املأ البيانات تلقائياً',
    dash_login_back: 'العودة للصفحة الرئيسية',

    // Status translation
    status_pending_payment: 'في انتظار الدفع',
    status_pending_booking: 'في انتظار الحجز',
    status_submitted: 'بانتظار المراجعة',
    status_under_review: 'قيد المراجعة',
    status_needs_info: 'يحتاج معلومات',
    status_patient_replied: 'رد المريض',
    status_approved: 'مقبول ومؤكد',
    status_declined: 'مرفوض',
    status_cancelled: 'ملغي',
    status_completed: 'مكتمل',
    status_booked: 'محجوز',

    // Patient Booking Flow
    booking_back: 'رجوع',
    booking_step_of: 'الخطوة {step} من {total}',
    booking_loading: 'جاري تحميل صفحة الحجز...',
    booking_prev: 'السابق',
    booking_skip: 'تخطى',
    booking_next: 'التالي',
    booking_next_save: 'التالي (حفظ البيانات)',
    booking_next_upload: 'التالي (رفع ومتابعة)',
    booking_confirm_review: 'تأكيد وإرسال للطبيب للمراجعة',
    booking_required_fields_warn: 'الرجاء إدخال الاسم، رقم الجوال، العمر، وإرفاق صورة الهوية الشخصية للمتابعة.',
    booking_complaint_warn: 'الرجاء شرح الشكوى الرئيسية للمتابعة.',
    booking_pain_warn: 'الرجاء تحديد مكان الألم على الخريطة أو اختيار "ألم منتشر".',
    booking_save_error: 'حصل خطأ أثناء حفظ البيانات، يرجى المحاولة مجدداً.',
    booking_upload_error: 'خطأ أثناء رفع الفحوصات والتحاليل الطبية.',
    booking_slot_error: 'حدث خطأ أثناء حجز الموعد',
    booking_payment_error: 'خطأ في الاتصال بالخادم لإعداد عملية الدفع.',
    booking_consulting_doctor: 'الطبيب الاستشاري',
    booking_full_name: 'الاسم الكامل للمريض',
    booking_name_placeholder: 'محمد عبدالله',
    booking_phone_label: 'رقم الجوال',
    booking_phone_placeholder: '05xxxxxxxx',
    booking_age_label: 'العمر',
    booking_age_placeholder: '35',
    booking_id_label: 'إثبات الهوية الشخصية (بطاقة الأحوال / الإقامة / جواز السفر)',
    booking_chief_complaint_q: 'ما هي الشكوى الرئيسية التي تعاني منها؟',
    booking_complaint_placeholder: 'مثال: ألم حاد في الركبة اليسرى يزداد عند صعود الدرج...',
    booking_pain_severity: 'شدّة الألم',
    booking_pain_nature_label: 'طبيعة الألم (يمكن اختيار أكثر من وصف)',
    booking_pain_location_label: 'مكان الألم على الجسم',
    booking_body_map_instructions: 'انقر على المنطقة في الجسم أو اختر من القائمة السريعة. للجانب الأيمن والأيسر، انقر على النقطة المناسبة.',
    booking_pain_duration_q: 'مدة الشكوى (سريعة)',
    booking_symptom_start_q: 'كيف بدأت الأعراض؟',
    booking_symptom_start_placeholder: 'مثال: بعد رفع ثقل، أو بدون سبب واضح',
    booking_previous_treatments_q: 'علاجات سابقة',
    booking_previous_treatments_placeholder: 'أدوية، علاج طبيعي، جبائر...',
    booking_previous_surgeries_q: 'عمليات جراحية سابقة',
    booking_previous_surgeries_placeholder: 'نوع العملية وتاريخها...',
    booking_aggravating_factors_q: 'العوامل التي تزيد الألم',
    booking_aggravating_factors_placeholder: 'مثال: صعود الدرج، الجلوس طويلاً...',
    booking_relieving_factors_q: 'العوامل التي تخفف الألم',
    booking_relieving_factors_placeholder: 'مثال: الراحة، الكمادات، مسكنات...',
    booking_joint_swelling_q: 'هل تعاني من تورم أو تيبس في المفاصل؟',
    booking_yes: 'نعم',
    booking_no: 'لا',
    booking_medical_history_q: 'التاريخ المرضي',
    booking_medical_history_placeholder: 'أمراض مزمنة، حساسية...',
    booking_current_medications_q: 'الأدوية الحالية',
    booking_current_medications_placeholder: 'اسم الدواء والجرعة...',
    booking_files_q: 'هل لديك أي ملفات طبية سابقة (أشعة، تحاليل، روشتات)؟',
    booking_files_desc: 'مشاركة الفحوصات السابقة تساعد الطبيب على تشخيص الحالة بشكل أدق.',
    booking_has_files_yes: 'نعم، لدي ملفات سابقة',
    booking_has_files_no: 'لا، لا توجد لدي ملفات',
    booking_upload_files_label: 'رفع الملفات الطبية',
    booking_packages_q: 'اختر الباقة المناسبة لاحتياجك',
    booking_packages_desc: 'كل باقة مصممة لتلبية احتياجات مختلفة. اختر ما يناسب حالتك.',
    booking_currency: 'ريال',
    booking_most_popular: 'الأكثر طلباً',
    booking_selected: 'تم الاختيار',
    booking_fees_label: 'رسوم الاستشارة',
    booking_fees_with: 'استشارة مع',
    booking_preparing_payment: 'جاري تجهيز رابط الدفع الآمن عبر Paymob...',
    booking_payment_gateway_error: 'تعذر الاتصال ببوابة الدفع',
    booking_payment_gateway_error_desc: 'يرجى إعادة تحميل الصفحة أو المحاولة لاحقاً.',
    booking_secure_payment_seal: 'الدفع مشفر وآمن 256-bit SSL',
    booking_powered_by: 'مدعوم من Paymob',
    booking_payment_success_title: 'تم استلام الدفع بنجاح',
    booking_payment_success_desc: 'اختر الوقت المناسب لجلستك مع الدكتور',
    booking_closed: 'مغلق',
    booking_available_times_for: 'الأوقات المتاحة ليوم',
    booking_loading_slots: 'جاري تحميل الأوقات...',
    booking_choose_date_prompt: 'الرجاء اختيار تاريخ من التقويم في الأعلى لعرض الأوقات المتاحة',
    booking_no_slots_warn: 'عذراً، لا توجد فترات عمل متاحة في هذا اليوم',
    booking_slot_reserved: 'محجوز',
    booking_selected_appt: 'الموعد المختار:',
    booking_at_time: 'في تمام الساعة',
    booking_awaiting_approval: 'بانتظار موافقة الطبيب',
    
    // Steps constants
    booking_step_0_label: 'بياناتك والتحقق',
    booking_step_0_sub: 'المعلومات الشخصية والهوية',
    booking_step_0_desc: 'أدخل معلوماتك الأساسية لبدء الاستشارة',
    booking_step_1_label: 'الشكوى الطبية',
    booking_step_1_sub: 'تفاصيل الحالة الصحية',
    booking_step_1_desc: 'صف حالتك الصحية بدقة حتى يساعدك الطبيب بشكل أفضل',
    booking_step_2_label: 'الأشعة والتحاليل',
    booking_step_2_sub: 'المستندات والفحوصات',
    booking_step_2_desc: 'ارفع ملفاتك الطبية إن وجدت (اختياري)',
    booking_step_3_label: 'اختيار الباقة',
    booking_step_3_sub: 'باقة الاستشارة',
    booking_step_3_desc: 'اختر الباقة المناسبة لاحتياجك الصحي',
    booking_step_4_label: 'الدفع',
    booking_step_4_sub: 'رسوم الاستشارة',
    booking_step_4_desc: 'ادفع رسوم الاستشارة',
    booking_step_5_label: 'الموعد',
    booking_step_5_sub: 'اختر وقتك',
    booking_step_5_desc: 'اختر الموعد المناسب من الأوقات المتاحة',
  },
  en: {
    // Navigation
    nav_home: 'Home',
    nav_about: 'About Dr.',
    nav_steps: 'Steps',
    nav_packages: 'Packages',
    nav_testimonials: 'Testimonials',
    nav_faq: 'FAQ',
    nav_start: 'Start Consultation',
    logo_sub: 'Orthopedic & Spine Consultant Online',
    footer_desc: 'An integrated medical consultation platform with Dr. Khalid Batterjee, providing excellent healthcare and a secure, reliable consultation experience from your home.',
    footer_links: 'Quick Links',
    footer_rights: 'All rights reserved',

    // Hero Section
    hero_badge: 'Batterjee Center for Specialized Medical Consultations',
    hero_title_dr: 'Dr. Khalid Batterjee',
    hero_title_title: 'Consultant Orthopedic & Spine Surgeon',
    hero_title_sub: 'Premium medical care for knee surgery, joint replacements, and arthroscopy online from your home',
    hero_para: 'The first integrated medical consultation platform combining consultant expertise with ease of technology. Book your video consultation in minutes, upload your medical files in complete privacy, and receive your diagnosis and treatment plan from home.',
    hero_btn_start: 'Start Consultation Now',
    hero_btn_about: 'Meet the Doctor',
    hero_status_online: 'Board Chairman (Available for booking)',

    // Hero Stats
    stat_experience_num: '35+',
    stat_experience_label: 'Years of Experience',
    stat_experience_desc: 'In orthopedic and spine surgery',
    stat_online_num: '100%',
    stat_online_label: 'Online Consultations',
    stat_online_desc: 'Video, secure & convenient',
    stat_satisfaction_num: '1,500+',
    stat_satisfaction_label: 'Patients Treated',
    stat_satisfaction_desc: 'With satisfaction rate exceeding 98%',

    // Expertise Bar
    exp_joints: 'Orthopedics & Spine Surgery',
    exp_scopes: 'Arthroscopic Surgery',
    exp_pain: 'Chronic Pain Treatment',
    exp_rehab: 'Post-Operative Rehab',
    exp_online: 'Online Consultations',

    // Achievement Counters
    counter_patients_label: 'Patients',
    counter_patients_sub: 'Consulted online',
    counter_experience_label: 'Years',
    counter_experience_sub: 'Of experience in medicine',
    counter_satisfaction_label: 'Satisfaction Rate',
    counter_satisfaction_sub: 'Exceeding 98% positive reviews',
    counter_response_label: 'Hours',
    counter_response_sub: 'Response time for queries',

    // Doctor Qualifications
    qual_label: 'Qualifications',
    qual_title: 'Experience extending over three decades',
    qual_desc: 'Dr. Khalid Batterjee has a rich biography of academic and practical achievements in the field of orthopedic and spine surgery, with more than 35 years of cumulative experience.',
    qual_btn: 'Book Consultation',
    qual_1991_title: 'Establishment of Batterjee Medical Center',
    qual_1991_inst: 'A vision to provide the best specialized medical services',
    qual_2012_title: 'Launching Integrated Clinics',
    qual_2012_inst: 'Expanding departments to include spine, rheumatology, and rehabilitation',
    qual_2020_title: 'Complete Digital Integration',
    qual_2020_inst: 'Converting all consultations into interactive remote video consultations',
    qual_2026_title: 'Developed Consultation System',
    qual_2026_inst: 'Launching the new platform, enabling secure medical storage and medicine delivery',

    // How it Works
    steps_label: 'How it Works',
    steps_title: 'Simple Steps to Book',
    steps_subtitle: 'From registration to the session with the doctor in 4 simple steps',
    step1_title: 'Book Consultation',
    step1_desc: 'Choose the medical package suitable for your condition to start booking',
    step2_title: 'Record Medical Data',
    step2_desc: 'Fill in your personal information and upload x-rays and lab tests in minutes',
    step3_title: 'Pay Securely',
    step3_desc: 'Pay via secure and fast electronic payment gateways',
    step4_title: 'Book Appointment & Connect',
    step4_desc: 'Choose the suitable appointment for your direct video session with the doctor',

    // Packages & Pricing
    pricing_label: 'Packages & Pricing',
    pricing_title: 'Choose the Right Package',
    pricing_subtitle: 'Flexible consultations at competitive prices to suit all cases',
    pkg_popular: 'Most Popular',
    pkg_basic_label: 'Basic Package',
    pkg_advanced_label: 'Premium Package',
    pkg_btn_choose: 'Choose Package',
    pkg_btn_book: 'Book Now',
    currency_sar: 'SAR',

    pkg_basic_title: 'Basic Consultation',
    pkg_basic_desc: 'A comprehensive 30-minute consultation session with the doctor to accurately evaluate and diagnose your condition.',
    pkg_basic_f1: 'Basic checkup with the consultant',
    pkg_basic_f2: 'Review and analysis of x-rays and lab tests',
    pkg_basic_f3: 'Accurate medical diagnosis of the condition',
    pkg_basic_f4: 'Session duration: 30 minutes',
    pkg_basic_f5: 'Free follow-up for 10 days',

    pkg_comprehensive_title: 'Comprehensive Consultation & Plan',
    pkg_comprehensive_desc: 'An extended consultation with the preparation of an integrated treatment program and evaluation of the need for surgery.',
    pkg_comprehensive_f1: 'All features of the basic package',
    pkg_comprehensive_f2: 'Preparation of an integrated treatment plan',
    pkg_comprehensive_f3: 'Evaluation of the need for surgery',
    pkg_comprehensive_f4: 'Discussion of surgical and alternative options',
    pkg_comprehensive_f5: 'First follow-up free after surgery',

    pkg_followup_title: 'Multiple Follow-up Packages',
    pkg_followup_desc: 'Multiple sessions at a discounted price for patients requiring continuous follow-up after surgery.',
    pkg_followup_f1_template: '3-session package for {p3} SAR',
    pkg_followup_f2_template: '4-session package for {p4} SAR',
    pkg_followup_f3: 'Savings up to 200 SAR',
    pkg_followup_f4: 'Post-operative and sports injury follow-ups',
    pkg_followup_f5: 'High flexibility in booking appointments',

    // Why Choose Us
    why_label: 'Why Dr. Batterjee?',
    why_title: 'World-class medical care from your home',
    why_desc: 'We put you at the heart of healthcare. An integrated platform combining medical expertise with modern technology to provide a seamless and secure consultation experience.',
    why_btn: 'Start Now',
    why_stat_patients: 'Patients',
    why_stat_satisfaction: 'Satisfaction',
    why_stat_response: 'Hours Response',
    why_trust_p1_num: 'Certified Board',
    why_trust_p1_label: 'Canadian Board & British Fellowship',
    why_trust_p2_num: 'Secure Data',
    why_trust_p2_label: 'Full privacy & file encryption',
    why_trust_p3_num: 'Digital Rx',
    why_trust_p3_label: 'Digitally approved prescriptions',
    
    why_f1_title: 'Vast Medical Experience',
    why_f1_desc: 'Dr. Khalid Batterjee holds Canadian and British board certifications and fellowships with over 35 years of experience.',
    why_f2_title: 'Complete File Privacy',
    why_f2_desc: 'Full encryption of your medical files and x-rays in accordance with the highest medical cybersecurity standards.',
    why_f3_title: 'Instant Booking',
    why_f3_desc: 'Choose your convenient time directly from the doctor\'s live schedule with no waiting times.',
    why_f4_title: 'All Medical Formats Supported',
    why_f4_desc: 'Upload your reports and x-rays with ease in various medical formats, including DICOM files.',
    why_f5_title: 'Home Prescription Delivery',
    why_f5_desc: 'We send your digitally certified medical prescription and arrange home delivery of medicines.',
    why_f6_title: 'Secure & Certified Payment',
    why_f6_desc: 'Trusted Saudi payment options supporting Mada, Visa, Mastercard, and Apple Pay.',

    // Testimonials
    test_label: 'Patient Reviews',
    test_title: 'What Do Our Patients Say?',
    test_1_text: 'The center provides excellent care and distinguished medical expertise. I consulted Dr. Khalid Batterjee regarding my knee surgery, and his diagnosis was highly accurate, saving me the trouble of traveling.',
    test_1_name: 'Abdulrahman Al-Otaibi',
    test_1_title: 'Patient (Joint Surgery Clinic)',
    test_2_text: 'An extremely easy and fast booking experience. The best part is the ability to upload x-rays and MRI files for Dr. Khalid Batterjee to analyze and prescribe the right treatment without leaving home.',
    test_2_name: 'Noura Al-Dossari',
    test_2_title: 'Patient (Orthopedic Surgery)',
    test_3_text: 'Following my knee injury, I contacted Dr. Khalid Batterjee. He prepared a wonderful home rehabilitation program and followed up with me step-by-step until I returned to sports naturally.',
    test_3_name: 'Fahd Al-Subeaei',
    test_3_title: 'Patient (Orthopedic & Spine Surgery)',

    // Medical Library
    lib_label: 'Medical Library',
    lib_title: 'Health Resources for You',
    lib_desc: 'Medical articles and guidelines prepared by Dr. Khalid Batterjee to help you in your treatment journey',
    read_time_suffix: 'min read',

    // FAQ
    faq_label: 'FAQ',
    faq_title: 'Everything You Need to Know',
    faq_desc: 'Quick answers to the most common questions. If you have another question, feel free to contact us.',
    faq_1_q: 'How can I book a consultation at Batterjee Center?',
    faq_1_a: 'The process is simple and takes less than 5 minutes: fill in your medical details, attach your x-rays if any, pay the consultation fees securely, and choose your appointment from the doctor\'s live schedule to receive the video session link.',
    faq_2_q: 'What is the cost of a medical consultation?',
    faq_2_a_template: 'Costs vary depending on the checkup package: Basic checkup is {p1} SAR, Comprehensive checkup is {p2} SAR, and multiple follow-up packages start at {p3} SAR for 3 sessions.',
    faq_3_q: 'Can I follow up with the doctor for free after the session?',
    faq_3_a: 'Yes, all medical consultations include a free follow-up period valid for 10 days from the main session date to discuss test results or update the treatment plan.',
    faq_4_q: 'Is medicine delivery available for all patients?',
    faq_4_a: 'Yes, after your consultation, if the doctor writes a prescription, it is sent electronically, and we offer home delivery of medications in cooperation with major pharmacies.',
    faq_5_q: 'How do I upload my medical files and x-rays?',
    faq_5_a: 'While filling out the booking form, you will find a dedicated upload area where you can drag and drop reports and x-rays. Our system supports all major formats including PDF, JPG, PNG, and DICOM.',

    // Final CTA
    cta_badge: 'Start Your Treatment Today',
    cta_title: 'Consult Your Consultant Doctor from Home Today',
    cta_desc: 'Book your consultation now in minutes and start your treatment journey with your consultant doctor. World-class specialized medical care is at your fingertips.',
    cta_btn: 'Start Consultation',
    art_not_found: 'Article Not Found',
    art_not_found_desc: 'Sorry, the article you are looking for is currently unavailable or has been moved.',
    art_back: 'Back to Home',
    art_written_by: 'Written by:',
    art_published_in: 'Published in:',
    art_sidebar_q: 'Do you suffer from joint pain?',
    art_sidebar_desc: 'Book your consultation now with Dr. Khalid Batterjee from home to receive an accurate diagnosis and treatment plan via secure chat.',
    art_sidebar_btn: 'Start Consultation Now',
    art_related: 'Related Articles',

    // Doctor Dashboard Common
    dash_brand_name: 'Batterjee Center',
    dash_brand_sub: 'Control Panel',
    dash_brand_mark: 'B',
    dash_nav_title: 'Navigation',
    dash_nav_requests: 'Consultation Requests',
    dash_nav_settings: 'Clinic Settings',
    dash_doctor_section: 'Attending Doctor',
    dash_doctor_role: 'Doctor',
    dash_signout: 'Sign Out',
    dash_error_back: 'Back to Dashboard',
    dash_error_title: 'An unexpected error occurred. Please refresh the page.',
    dash_gate_checking_login: 'Checking login status...',
    dash_gate_loading_consults: 'Loading consultations...',
    dash_gate_loading_detail: 'Loading consultation details...',
    dash_gate_loading_dash: 'Loading dashboard...',

    // Dashboard Main Page
    dash_eyebrow: 'Shared Dashboard',
    dash_title_requests: 'Batterjee Medical Consultations',
    dash_title_settings: 'Schedule & Clinic Settings',
    dash_subtitle_requests: 'Track consultation requests and bookings efficiently with a clear view.',
    dash_subtitle_settings: 'Set working days, hours, and duration per doctor.',
    dash_total: 'Total',
    dash_consultations: 'Consultations',
    dash_filter_status_label: 'Status:',
    dash_filter_status_all: 'All',
    dash_reset_filters: 'Reset',
    dash_search_placeholder: 'Search by patient name, phone, or complaint...',
    dash_showing: 'Showing',
    dash_of: 'of',
    dash_table_patient: 'Patient',
    dash_table_complaint: 'Chief Complaint',
    dash_table_status: 'Status',
    dash_table_date: 'Date',
    dash_empty_title: 'No matching consultations',
    dash_empty_desc: 'Try adjusting your filter or search criteria.',
    dash_patient_years: 'years old',
    dash_save_success: 'Appointment settings and schedule saved successfully!',
    dash_working_days: 'Weekly Working Days',
    dash_daily_hours: 'Daily Working Hours',
    dash_start_time: 'Start Time',
    dash_end_time: 'End Time',
    dash_break_hours: 'Break / Lunch Period',
    dash_break_start: 'Break Start',
    dash_break_end: 'Break End',
    dash_slot_duration: 'Consultation Duration',
    dash_prices_title: 'Session & Consultation Prices',
    dash_price_basic: 'Basic Consultation Price (SAR)',
    dash_price_comprehensive: 'Comprehensive Consultation Price (SAR)',
    dash_price_pkg3: '3-Session Follow-up Price (SAR)',
    dash_price_pkg4: '4-Session Follow-up Price (SAR)',
    dash_price_promo: 'Multi-Follow-up & Promo Price (SAR)',
    dash_gcal_title: 'Google Calendar Integration',
    dash_gcal_desc: 'When Google Calendar is connected, busy slots are automatically hidden from patients, and events are created in your calendar upon booking.',
    dash_gcal_connected: 'Connected',
    dash_gcal_disconnect: 'Disconnect',
    dash_gcal_connect: 'Connect Google Calendar',
    dash_gcal_warning: 'To activate integration, add Google OAuth credentials in env variables:',
    dash_save_changes: 'Save Changes & Schedule',
    dash_saving: 'Saving...',
    dash_slot_15: '15 minutes',
    dash_slot_30: '30 minutes',
    dash_slot_45: '45 minutes',
    dash_slot_60: '60 minutes (full hour)',

    // Dashboard Detail Page
    dash_detail_back: 'Back to Dashboard',
    dash_detail_title: 'Consultation Details:',
    dash_detail_doctor_kicker: 'Attending Doctor',
    dash_detail_appt_label: 'Appointment',
    dash_btn_start_review: 'Start Review',
    dash_btn_approve: 'Approve & Confirm',
    dash_btn_ask_info: 'Request Info',
    dash_btn_reject: 'Decline',
    dash_btn_start_close: 'Start Consultation & Close',
    dash_btn_reschedule: 'Reschedule',
    dash_btn_cancel: 'Cancel',
    dash_btn_view_as_patient: 'View as Patient',
    dash_panel_patient_info: 'Patient Info & Complaint',
    dash_info_name: 'Name',
    dash_info_phone: 'Phone',
    dash_info_age: 'Age',
    dash_chief_complaint_label: 'Chief Complaint',
    dash_panel_pain_eval: 'Pain Assessment',
    dash_pain_nature: 'Pain Nature',
    dash_pain_locations: 'Pain Locations',
    dash_panel_files: 'Attached Files',
    dash_files_empty: 'No attached files',
    dash_id_card_label: 'ID Card',
    dash_file_open: 'Open',
    dash_panel_chat: 'Chat with Patient',
    dash_chat_empty: 'No messages yet. Start the conversation by sending a message or requesting information.',
    dash_chat_me: 'Me (Doctor)',
    dash_chat_placeholder: 'Type a message to the patient...',
    dash_chat_send: 'Send',
    dash_chat_templates: 'Quick Templates',
    dash_panel_notes: 'Doctor Notes (Private)',
    dash_notes_placeholder: 'Your private notes about this case...',
    dash_notes_save: 'Save Notes',
    dash_notes_saved_at: 'Saved at',
    dash_cancellation_reason_title: 'Cancellation/Rejection Reason',
    dash_confirm_reschedule: 'Reschedule Appointment',
    dash_confirm_new_date: 'New Date',
    dash_confirm_new_time: 'New Time',
    dash_confirm_btn_confirm: 'Confirm',
    dash_confirm_btn_cancel: 'Cancel',
    dash_confirm_approve_title: 'Confirm Consultation Acceptance',
    dash_confirm_approve_desc: 'The consultation will be accepted and the appointment confirmed.',
    dash_confirm_approve_btn: 'Confirm Acceptance',
    dash_confirm_approve_back: 'Back',
    dash_confirm_cancel_title: 'Cancel Consultation',
    dash_confirm_cancel_placeholder: 'Cancellation reason (will be shown to patient)...',
    dash_confirm_cancel_btn: 'Confirm Cancellation',
    dash_confirm_reject_title: 'Decline Consultation Request',
    dash_confirm_reject_placeholder: 'Rejection reason (optional, will be shown to patient)...',
    dash_confirm_reject_btn: 'Confirm Decline',

    // Login Page
    dash_login_title: 'Doctor Dashboard',
    dash_login_sub: 'Log in to access consultations and manage appointments',
    dash_login_email: 'Email',
    dash_login_password: 'Password',
    dash_login_btn: 'Log In',
    dash_login_loading: 'Logging in...',
    dash_login_error_missing: 'Please enter both email and password.',
    dash_login_test_hint: 'For testing use the test account:',
    dash_login_fill_btn: 'Auto-fill credentials',
    dash_login_back: 'Back to Main Page',

    // Status translation
    status_pending_payment: 'Pending Payment',
    status_pending_booking: 'Pending Booking',
    status_submitted: 'Awaiting Review',
    status_under_review: 'Under Review',
    status_needs_info: 'Needs Info',
    status_patient_replied: 'Patient Replied',
    status_approved: 'Approved & Confirmed',
    status_declined: 'Declined',
    status_cancelled: 'Cancelled',
    status_completed: 'Completed',
    status_booked: 'Booked',

    // Patient Booking Flow
    booking_back: 'Back',
    booking_step_of: 'Step {step} of {total}',
    booking_loading: 'Loading booking page...',
    booking_prev: 'Previous',
    booking_skip: 'Skip',
    booking_next: 'Next',
    booking_next_save: 'Next (Save Info)',
    booking_next_upload: 'Next (Upload & Continue)',
    booking_confirm_review: 'Confirm & Send to Doctor for Review',
    booking_required_fields_warn: 'Please enter name, phone number, age, and attach your ID photo to continue.',
    booking_complaint_warn: 'Please explain your chief complaint to continue.',
    booking_pain_warn: 'Please select a pain location on the map or select "widespread pain".',
    booking_save_error: 'An error occurred while saving details. Please try again.',
    booking_upload_error: 'Error uploading medical scans and tests.',
    booking_slot_error: 'An error occurred while booking the appointment.',
    booking_payment_error: 'Error connecting to server to prepare payment.',
    booking_consulting_doctor: 'Consulting Doctor',
    booking_full_name: 'Patient Full Name',
    booking_name_placeholder: 'Mohamed Abdullah',
    booking_phone_label: 'Phone Number',
    booking_phone_placeholder: '05xxxxxxxx',
    booking_age_label: 'Age',
    booking_age_placeholder: '35',
    booking_id_label: 'Proof of Identity (ID Card / Iqama / Passport)',
    booking_chief_complaint_q: 'What is the chief complaint you are experiencing?',
    booking_complaint_placeholder: 'Example: Sharp pain in the left knee that increases when climbing stairs...',
    booking_pain_severity: 'Pain Severity',
    booking_pain_nature_label: 'Pain Nature (you can select more than one description)',
    booking_pain_location_label: 'Pain Location on Body',
    booking_body_map_instructions: 'Click on the body area or select from the quick list. For left/right sides, click the appropriate spot.',
    booking_pain_duration_q: 'Complaint Duration (Quick Select)',
    booking_symptom_start_q: 'How did symptoms start?',
    booking_symptom_start_placeholder: 'Example: After lifting a weight, or without an obvious reason',
    booking_previous_treatments_q: 'Previous Treatments',
    booking_previous_treatments_placeholder: 'Medications, physical therapy, splints...',
    booking_previous_surgeries_q: 'Previous Surgeries',
    booking_previous_surgeries_placeholder: 'Type of surgery and date...',
    booking_aggravating_factors_q: 'Aggravating Factors',
    booking_aggravating_factors_placeholder: 'Example: Climbing stairs, sitting for a long time...',
    booking_relieving_factors_q: 'Relieving Factors',
    booking_relieving_factors_placeholder: 'Example: Rest, compresses, pain relievers...',
    booking_joint_swelling_q: 'Do you experience joint swelling or stiffness?',
    booking_yes: 'Yes',
    booking_no: 'No',
    booking_medical_history_q: 'Medical History',
    booking_medical_history_placeholder: 'Chronic diseases, allergies...',
    booking_current_medications_q: 'Current Medications',
    booking_current_medications_placeholder: 'Medication name and dose...',
    booking_files_q: 'Do you have any previous medical files (scans, tests, prescriptions)?',
    booking_files_desc: 'Sharing previous scans/reports helps the doctor diagnose your condition more accurately.',
    booking_has_files_yes: 'Yes, I have previous files',
    booking_has_files_no: 'No, I don\'t have files',
    booking_upload_files_label: 'Upload Medical Files',
    booking_packages_q: 'Choose the suitable package for your needs',
    booking_packages_desc: 'Each package is designed to meet different needs. Choose what fits your case.',
    booking_currency: 'SAR',
    booking_most_popular: 'Most Popular',
    booking_selected: 'Selected',
    booking_fees_label: 'Consultation Fee',
    booking_fees_with: 'Consultation with',
    booking_preparing_payment: 'Preparing secure payment link via Paymob...',
    booking_payment_gateway_error: 'Could not connect to payment gateway',
    booking_payment_gateway_error_desc: 'Please reload the page or try again later.',
    booking_secure_payment_seal: 'Encrypted and secure 256-bit SSL payment',
    booking_powered_by: 'Powered by Paymob',
    booking_payment_success_title: 'Payment received successfully',
    booking_payment_success_desc: 'Choose the suitable time for your session with the doctor',
    booking_closed: 'Closed',
    booking_available_times_for: 'Available times for',
    booking_loading_slots: 'Loading times...',
    booking_choose_date_prompt: 'Please choose a date from the calendar above to view available times',
    booking_no_slots_warn: 'Sorry, there are no working slots available on this day',
    booking_slot_reserved: 'Booked',
    booking_selected_appt: 'Selected appointment:',
    booking_at_time: 'at',
    booking_awaiting_approval: 'Awaiting doctor\'s approval',
    
    // Steps constants
    booking_step_0_label: 'Your Details & Verification',
    booking_step_0_sub: 'Personal Info & ID',
    booking_step_0_desc: 'Enter your basic details to start the consultation',
    booking_step_1_label: 'Medical Complaint',
    booking_step_1_sub: 'Health Details',
    booking_step_1_desc: 'Describe your condition accurately to help the doctor diagnose you better',
    booking_step_2_label: 'Scans & Reports',
    booking_step_2_sub: 'Documents & Scans',
    booking_step_2_desc: 'Upload your previous medical files if any (optional)',
    booking_step_3_label: 'Choose Package',
    booking_step_3_sub: 'Consultation Package',
    booking_step_3_desc: 'Select the suitable package for your health needs',
    booking_step_4_label: 'Payment',
    booking_step_4_sub: 'Consultation Fees',
    booking_step_4_desc: 'Pay consultation fees',
    booking_step_5_label: 'Appointment',
    booking_step_5_sub: 'Choose Your Time',
    booking_step_5_desc: 'Select a suitable slot from the available times',
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>('ar')

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const savedLang = localStorage.getItem('lang') as Language
      if (savedLang === 'ar' || savedLang === 'en') {
        setTimeout(() => {
          setLang(savedLang)
        }, 0)
      }
    }
  }, [])

  const handleSetLang = (newLang: Language) => {
    setLang(newLang)
    if (typeof window !== 'undefined') {
      localStorage.setItem('lang', newLang)
    }
  }

  useEffect(() => {
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'
    document.documentElement.lang = lang
  }, [lang])

  const t = (key: string): string => {
    const dict = translations[lang] as Record<string, string>
    return dict[key] || key
  }

  const isRtl = lang === 'ar'

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t, isRtl }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
